### PR TITLE
Code rewrite & parallelization

### PR DESCRIPTION
**Pull request by SquishyStrawberry**
I've rewritten most of the code, while keeping the original functionality intact.

I have also added some extra logging with *wacky* colors, and parallellized the code with coroutines using `eventlet`.

To run the new code you have to run `python3 -m pip install --user -r requirements.txt` before anything else, then you can just do `python3 xkcd.py` as usual.

### CODE REVIEW

**Comment by keatinge** [comment]
Lot of complicated stuff in here and it does improve the speed but I'm getting an error for the range 1-1000

```
Admin@Admin-PC MINGW64 ~/Desktop
$ python 1.py
Enter the number or range of comics to download: 1-1000
```

```
Traceback (most recent call last):
  File "1.py", line 137, in <module>
    main()
  File "1.py", line 119, in main
    successful, failed, to_go = save_comics(start_num, end_num)
  File "1.py", line 85, in save_comics
    for (num, exception) in p.imap(save_comic, comic_numbers):
  File "C:\Python\lib\site-packages\eventlet\greenpool.py", line 238, in next
    val = self.waiters.get().wait()
  File "C:\Python\lib\site-packages\eventlet\greenthread.py", line 175, in wait
    return self._exit_event.wait()
  File "C:\Python\lib\site-packages\eventlet\event.py", line 121, in wait
    return hubs.get_hub().switch()
  File "C:\Python\lib\site-packages\eventlet\hubs\hub.py", line 294, in switch
    return self.greenlet.switch()
  File "C:\Python\lib\site-packages\eventlet\hubs\hub.py", line 346, in run
    self.wait(sleep_time)
  File "C:\Python\lib\site-packages\eventlet\hubs\selects.py", line 38, in wait
    r, w, er = select.select(readers.keys(), writers.keys(), all_fds, seconds)
ValueError: too many file descriptors in select()
```

**Comment by SquishyStrawberry** [comment]
@keatinge The issue seems to appear to be a Windows only issue. Could you please try and increment the amount of values in the range (e.g. `1-500`, then `1-600`, etc...) until you can reproduce this error with the lowest possible value?

By the way, the issue is related to opening too many sockets at the same time.

Once you do that, I'll add a fix for it in my pull request :+1: .

**Comment by SquishyStrawberry** [comment]
I've tried adding a fix for it, but still follow the instructions I told you before updating to the latest version.

Also, I believe the other *stilystic* changes you mentioned are purely subjective, I was just following **my** coding style.

**Comment by SquishyStrawberry** [comment]
@keatinge Woops, nevermind, I found a resource on the internet. Apparently it is, as stated in the comment that I left on the code, by default 64 on Windows systems but is somehow extended to 256 or 512 via Python.

So, now it should work without any issues, can you confirm this & close the discussion?

**Comment by keatinge** [comment]
Okay the comic it breaks on is 513. 1-512 downloads fine, 1-513 has the error. https://xkcd.com/513/

I agree with you that stylistic things are purely subjective but readability counts and it's better to have one project follow the same stylistic guidelines throughout.

**Comment by SquishyStrawberry** [comment]
@keatinge Does it still crash even with the new update?

**Comment by keatinge** [comment]
Just tested, the new update fixes it

**Comment by SquishyStrawberry** [comment]
Awesome, you gonna merge?

**Comment by keatinge** [comment]
Yeah sure, I'll fix the little things in a different commit

**Pull request merged**
